name: Run Unit Tests on PR

on:
  pull_request:
    branches:
      - main
      - develop  # Add other branches if needed

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'corretto' or 'zulu' if needed
          java-version: '21'
          cache: maven  # Speeds up builds by caching dependencies

      - name: Install dependencies
        run: mvn dependency:resolve

      - name: Run unit tests
        run: mvn test